### ISSUE TITLE
Crash for VPN when trying to re-authenticate after 1 hour of being turned ON

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#1735]
**VPN version:**

* 2.5.0 (2.202109031602)

**Affected Platforms:**

* Linux Ubuntu Focal;
* Android 10;

**Prerequisites:**

* Have one FxA account with subscription for Mozilla VPN;
* Have the VPN installed and opened on your machine;

**Steps to reproduce:**
1.Turn ON the VPN;
2. Wait aprox 1 hour;
3. Sign out from the app;
4. Click “Get Started”

**Expected result:**

* You are redirected to the auth screen.

**Actual result:**

* The app crashes.

**Notes:**

* Not reproducing for less time;
* attaching logs.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-954)

**Comment by data-sync-user** [comment]
➤ Owen Kirby commented:

I’ve been able to reproduce this, with the following backtrace

#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f51f6bc9859 in __GI_abort () at abort.c:79
#2  0x00000000016731c6 in  ()
#3  0x0000000001673afb in QMessageLogger::fatal(char const*, ...) const ()
#4  0x00000000016707fc in qt_assert_x(char const*, char const*, char const*, int) ()
#5  0x0000000000448ac7 in AuthenticationListener::create(QObject*, MozillaVPN::AuthenticationType)
    (parent=0x43b4a00, authenticationType=(MozillaVPN::AuthenticationInBrowser | unknown: 32592))
    at authenticationlistener.cpp:46
#6  0x00000000005274f5 in TaskAuthenticate::run(MozillaVPN*) (this=0x43b4a00, vpn=0x7ffc34a73070)
    at tasks/authenticate/taskauthenticate.cpp:65
#7  0x00000000004f6711 in MozillaVPN::maybeRunTask() (this=0x7ffc34a73070) at mozillavpn.cpp:511
#8  0x00000000004f6a41 in MozillaVPN::taskCompleted() (this=0x7ffc34a73070) at mozillavpn.cpp:522
#9  0x0000000000475624 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (MozillaVPN::*)()>::call(void (MozillaVPN::*)(), MozillaVPN*, void**)
    (f=(void (MozillaVPN::*)(class MozillaVPN * const)) 0x4f6960 <MozillaVPN::taskCompleted()>, o=0x7ffc34a73070, arg=0x7ffc34a71f80) at /opt/qt-everywhere-5.15.1/include/QtCore/qobjectdefs_impl.h:152
#10 0x0000000000475598 in QtPrivate::FunctionPointer<void (MozillaVPN::*)()>::call<QtPrivate::List<>, void>(void (MozillaVPN::*)(), MozillaVPN*, void**)
    (f=(void (MozillaVPN::*)(class MozillaVPN * const)) 0x4f6960 <MozillaVPN::taskCompleted()>, o=0x7ffc34a73070, arg=0x7ffc34a71f80) at /opt/qt-everywhere-5.15.1/include/QtCore/qobjectdefs_impl.h:185
#11 0x00000000004754c5 in QtPrivate::QSlotObject<void (MozillaVPN::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*)
    (which=1, this_=0x3bdc0a0, r=0x7ffc34a73070, a=0x7ffc34a71f80, ret=0x0)
    at /opt/qt-everywhere-5.15.1/include/QtCore/qobjectdefs_impl.h:418
#12 0x00000000017f7b44 in void doActivate<false>(QObject*, int, void**) ()
#13 0x0000000000582d52 in Task::completed() (this=0x37d5bb0) at .moc/moc_task.cpp:131
#14 0x000000000052df15 in TaskHeartbeat::run(MozillaVPN*)::$_1::operator()(QByteArray const&) const
    (this=0x43c1110, data=...) at tasks/heartbeat/taskheartbeat.cpp:66
#15 0x000000000052dc54 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<QByteArray const&>, void, TaskHeartbeat::run(MozillaVPN*)::$_1>::call(TaskHeartbeat::run(MozillaVPN*)::$_1&, void**)
    (f=..., arg=0x7ffc34a72240) at /opt/qt-everywhere-5.15.1/include/QtCore/qobjectdefs_impl.h:146
#16 0x000000000052dc21 in QtPrivate::Functor<TaskHeartbeat::run(MozillaVPN*)::$_1, 1>::call<QtPrivate::List<QByteArray const&>, void>(TaskHeartbeat::run(MozillaVPN*)::$_1&, void*, void**) (f=..., arg=0x7ffc34a72240)
    at /opt/qt-everywhere-5.15.1/include/QtCore/qobjectdefs_impl.h:256
#17 0x000000000052dbcc in QtPrivate::QFunctorSlotObject<TaskHeartbeat::run(MozillaVPN*)::$_1, 1, QtPrivate::List<QByteArray const&>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*)
    (which=1, this_=0x43c1100, r=0x4541570, a=0x7ffc34a72240, ret=0x0)
    at /opt/qt-everywhere-5.15.1/include/QtCore/qobjectdefs_impl.h:443
#18 0x00000000017f7b44 in void doActivate<false>(QObject*, int, void**) ()
#19 0x000000000057f7d9 in NetworkRequest::requestCompleted(QByteArray const&) (this=0x4541570, _t1=...)
    at .moc/moc_networkrequest.cpp:232
#20 0x000000000050a1db in NetworkRequest::replyFinished() (this=0x4541570) at networkrequest.cpp:757
#21 0x000000000050afa4 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (NetworkRequest::*)()>::call(void (NetworkRequest::*)(), NetworkRequest*, void**)
    (f=(void (NetworkRequest::*)(class NetworkRequest * const)) 0x509d50 <NetworkRequest::replyFinished()>, o=0x4541570, arg=0x7ffc34a72520) at /opt/qt-everywhere-5.15.1/include/QtCore/qobjectdefs_impl.h:152
#22 0x000000000050af18 in QtPrivate::FunctionPointer<void (NetworkRequest::*)()>::call<QtPrivate::List<>, void>(void (NetworkRequest::*)(), NetworkRequest*, void**)
    (f=(void (NetworkRequest::*)(class NetworkRequest * const)) 0x509d50 <NetworkRequest::replyFinished()>, o=0x4541570, arg=0x7ffc34a72520) at /opt/qt-everywhere-5.15.1/include/QtCore/qobjectdefs_impl.h:185
#23 0x000000000050ae45 in QtPrivate::QSlotObject<void (NetworkRequest::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*)
    (which=1, this_=0x3d92e10, r=0x4541570, a=0x7ffc34a72520, ret=0x0)
    at /opt/qt-everywhere-5.15.1/include/QtCore/qobjectdefs_impl.h:418
#24 0x00000000017f7b44 in void doActivate<false>(QObject*, int, void**) ()
#25 0x00000000015c8936 in QNetworkReplyHttpImplPrivate::finished() ()
#26 0x00000000017f0b92 in QObject::event(QEvent*) ()
#27 0x000000000095b70d in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
#28 0x000000000095ca64 in QApplication::notify(QObject*, QEvent*) ()
#29 0x00000000017cf6fc in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
#30 0x00000000017d0734 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
#31 0x0000000001813553 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) ()
#32 0x00007f51f701d17d in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007f51f701d400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#34 0x00007f51f701d4a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#35 0x0000000001812e88 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#36 0x00000000017cb9c6 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
#37 0x00000000017cfc90 in QCoreApplication::exec() ()
#38 0x0000000000471252 in CommandUI::run(QStringList&)::$_0::operator()() const (this=0x7ffc34a733e0)
    at commands/commandui.cpp:503
#39 0x000000000046fd1d in std::_Function_handler<int (), CommandUI::run(QStringList&)::$_0>::_M_invoke(std::_Any_data const&) (__functor=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:285
#40 0x000000000045e78e in std::function<int ()>::operator()() const (this=0x7ffc34a733e0)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:688
#41 0x000000000045ea76 in Command::runQmlApp(std::function<int ()>&&) (this=0x3622b60, a_callback=...)
    at command.cpp:166
#42 0x000000000046fb3e in CommandUI::run(QStringList&) (this=0x3622b60, tokens=...) at commands/commandui.cpp:85
#43 0x0000000000460b07 in CommandLineParser::parse(int, char**) (this=
    0x7ffc34a73708, argc=1, argv=0x7ffc34a73828) at commandlineparser.cpp:85
#44 0x00000000004d287d in main(int, char**) (argc=1, argv=0x7ffc34a73828) at main.cpp:15
#45 0x00007f51f6bcb0b3 in __libc_start_main (main=
    0x4d2840 <main(int, char**)>, argc=1, argv=0x7ffc34a73828, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc34a73818) at ../csu/libc-start.c:308
#46 0x000000000043ee7e in _start ()

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on both Linux and Android using the last builds from release branch. (2.5.0 - 2.202109080823).

The app does not crash after following above steps.
