### ISSUE TITLE
Crash in qmlengineholder DTOR with Qt6.2

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#2306]
┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1358)

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

Maybe I'm wrong, but it seems that the crash is related to the LinearGradient QML object.
Removing this, the crash goes away.

**Comment by flozia** [comment]
I remember seeing the error message described in the title of the issue once, but haven’t come across it since. Is this still reproducible for you @bakulf?

**Comment by flozia** [comment]
Closing since we can’t reproduce this issue currently.

**Comment by bakulf** [comment]
I can still reproduce this issue:

```
Thread 1 received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=139777297504704) at pthread_kill.c:44
44	pthread_kill.c: No such file or directory.
(rr) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139777297504704) at pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=139777297504704) at pthread_kill.c:80
#2  __GI___pthread_kill (threadid=139777297504704, signo=signo@entry=6) at pthread_kill.c:91
#3  0x00007f20734a0476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f20734867b7 in __GI_abort () at abort.c:79
#5  0x00007f20734e75e6 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f207363913d "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#6  0x00007f20734feadc in malloc_printerr (str=str@entry=0x7f207363bbc8 "malloc_consolidate(): unaligned fastbin chunk detected") at malloc.c:5543
#7  0x00007f20734ffd7c in malloc_consolidate (av=av@entry=0x7f2073672c60 <main_arena>) at malloc.c:4637
#8  0x00007f2073500870 in _int_free (av=0x7f2073672c60 <main_arena>, p=0x56107b92bd10, have_lock=<optimized out>) at malloc.c:4561
#9  0x00007f2073502ce5 in __GI___libc_free (mem=<optimized out>) at malloc.c:3278
#10 0x00007f2073aae313 in QTypedArrayData<char16_t>::deallocate(QArrayData*) (data=<optimized out>) at /home/qt/work/qt/qtbase/src/corelib/tools/qarraydata.h:157
#11 QArrayDataPointer<char16_t>::~QArrayDataPointer() (this=0x56107b96d1b8, __in_chrg=<optimized out>) at /home/qt/work/qt/qtbase/src/corelib/tools/qarraydatapointer.h:131
#12 QString::~QString() (this=0x56107b96d1b8, __in_chrg=<optimized out>) at /home/qt/work/qt/qtbase/src/corelib/text/qstring.h:1282
#13 QUrlPrivate::~QUrlPrivate() (this=0x56107b96d150, __in_chrg=<optimized out>) at /home/qt/work/qt/qtbase/src/corelib/io/qurl.cpp:613
#14 QUrl::~QUrl() (this=<optimized out>, __in_chrg=<optimized out>) at /home/qt/work/qt/qtbase/src/corelib/io/qurl.cpp:1860
#15 QUrl::~QUrl() (this=<optimized out>, __in_chrg=<optimized out>) at /home/qt/work/qt/qtbase/src/corelib/io/qurl.cpp:1857
#16 0x00007f2075efd591 in QQuickShaderEffectImpl::~QQuickShaderEffectImpl() (this=0x56107ae8ba90, __in_chrg=<optimized out>) at /home/qt/work/qt/qtdeclarative/src/quick/items/qquickshadereffect.cpp:974
#17 0x00007f2075efd63f in QQuickShaderEffectImpl::~QQuickShaderEffectImpl() (this=0x56107ae8ba90, __in_chrg=<optimized out>) at /home/qt/work/qt/qtdeclarative/src/quick/items/qquickshadereffect.cpp:974
#18 QQuickShaderEffect::~QQuickShaderEffect() (this=this@entry=0x56107ae8b7f0, __in_chrg=<optimized out>) at /home/qt/work/qt/qtdeclarative/src/quick/items/qquickshadereffect.cpp:682
#19 0x00007f2075e18895 in QQmlPrivate::QQmlElement<QQuickShaderEffect>::~QQmlElement() (this=0x56107ae8b7f0, __in_chrg=<optimized out>) at /home/qt/work/qt/qtdeclarative/src/qml/qml/qqmlprivate.h:133
#20 QQmlPrivate::QQmlElement<QQuickShaderEffect>::~QQmlElement() (this=0x56107ae8b7f0, __in_chrg=<optimized out>) at /home/qt/work/qt/qtdeclarative/src/qml/qml/qqmlprivate.h:133
#21 0x00007f2073b4744a in QObjectPrivate::deleteChildren() (this=this@entry=0x56107aeaa1c0) at /home/qt/work/qt/qtbase/src/corelib/kernel/qobject.cpp:2106
#22 0x00007f2073b4ba85 in QObject::~QObject() (this=this@entry=0x56107aecec40, __in_chrg=<optimized out>) at /home/qt/work/qt/qtbase/src/corelib/kernel/qobject.cpp:1115
#23 0x00007f2075c4f818 in QQuickItem::~QQuickItem() (this=this@entry=0x56107aecec40, __in_chrg=<optimized out>) at /home/qt/work/qt/qtdeclarative/src/quick/items/qquickitem.cpp:2339
#24 0x00007f2075e18675 in QQmlPrivate::QQmlElement<QQuickItem>::~QQmlElement() (this=0x56107aecec40, __in_chrg=<optimized out>) at /home/qt/work/qt/qtdeclarative/src/qml/qml/qqmlprivate.h:133
#25 QQmlPrivate::QQmlElement<QQuickItem>::~QQmlElement() (this=0x56107aecec40, __in_chrg=<optimized out>) at /home/qt/work/qt/qtdeclarative/src/qml/qml/qqmlprivate.h:133
#26 0x00007f2073b4744a in QObjectPrivate::deleteChildren() (this=this@entry=0x56107a986e30) at /home/qt/work/qt/qtbase/src/corelib/kernel/qobject.cpp:2106
#27 0x00007f2073b4ba85 in QObject::~QObject() (this=this@entry=0x56107aecd5f0, __in_chrg=<optimized out>) at /home/qt/work/qt/qtbase/src/corelib/kernel/qobject.cpp:1115
#28 0x00007f2075c4f818 in QQuickItem::~QQuickItem() (this=this@entry=0x56107aecd5f0, __in_chrg=<optimized out>) at /home/qt/work/qt/qtdeclarative/src/quick/items/qquickitem.cpp:2339
#29 0x00007f2075e1950e in QQuickRectangle::~QQuickRectangle() (this=0x56107aecd5f0, __in_chrg=<optimized out>)
    at /home/qt/work/qt/qtdeclarative/include/QtQuick/6.2.0/QtQuick/private/../../../../../src/quick/items/qquickrectangle_p.h:164
#30 QQmlPrivate::QQmlElement<QQuickRectangle>::~QQmlElement() (this=0x56107aecd5f0, __in_chrg=<optimized out>) at /home/qt/work/qt/qtdeclarative/src/qml/qml/qqmlprivate.h:133
#31 QQmlPrivate::QQmlElement<QQuickRectangle>::~QQmlElement() (this=0x56107aecd5f0, __in_chrg=<optimized out>) at /home/qt/work/qt/qtdeclarative/src/qml/qml/qqmlprivate.h:133
#32 0x00007f2073b4744a in QObjectPrivate::deleteChildren() (this=this@entry=0x56107aec4860) at /home/qt/work/qt/qtbase/src/corelib/kernel/qobject.cpp:2106
#33 0x00007f2073b4ba85 in QObject::~QObject() (this=this@entry=0x56107ab486c0, __in_chrg=<optimized out>) at /home/qt/work/qt/qtbase/src/corelib/kernel/qobject.cpp:1115
#34 0x00007f2075c4f818 in QQuickItem::~QQuickItem() (this=this@entry=0x56107ab486c0, __in_chrg=<optimized out>) at /home/qt/work/qt/qtdeclarative/src/quick/items/qquickitem.cpp:2339
#35 0x00007f202268a1b3 in QQuickControl::~QQuickControl() (this=this@entry=0x56107ab486c0, __in_chrg=<optimized out>) at /home/qt/work/qt/qtdeclarative/src/quicktemplates2/qquickcontrol.cpp:869
#36 0x00007f2022666a9f in QQuickAbstractButton::~QQuickAbstractButton() (this=this@entry=0x56107ab486c0, __in_chrg=<optimized out>) at /home/qt/work/qt/qtdeclarative/src/quicktemplates2/qquickabstractbutton.cpp:467
#37 0x00007f202270f8ce in QQuickButton::~QQuickButton() (this=0x56107ab486c0, __in_chrg=<optimized out>)
    at /home/qt/work/qt/qtdeclarative/include/QtQuickTemplates2/6.2.0/QtQuickTemplates2/private/../../../../../src/quicktemplates2/qquickbutton_p.h:57
#38 QQmlPrivate::QQmlElement<QQuickButton>::~QQmlElement() (this=0x56107ab486c0, __in_chrg=<optimized out>) at /home/qt/work/qt/qtdeclarative/src/qml/qml/qqmlprivate.h:133
#39 QQmlPrivate::QQmlElement<QQuickButton>::~QQmlElement() (this=0x56107ab486c0, __in_chrg=<optimized out>) at /home/qt/work/qt/qtdeclarative/src/qml/qml/qqmlprivate.h:133
#40 0x00007f2073b4744a in QObjectPrivate::deleteChildren() (this=this@entry=0x56107ab4db20) at /home/qt/work/qt/qtbase/src/corelib/kernel/qobject.cpp:2106
#41 0x00007f2073b4ba85 in QObject::~QObject() (this=this@entry=0x56107ae77aa0, __in_chrg=<optimized out>) at /home/qt/work/qt/qtbase/src/corelib/kernel/qobject.cpp:1115
#42 0x00007f2074a34556 in QWindow::~QWindow() (this=this@entry=0x56107ae77aa0, __in_chrg=<optimized out>) at /home/qt/work/qt/qtbase/src/gui/kernel/qwindow.cpp:218
#43 0x00007f2075cde3d3 in QQuickWindow::~QQuickWindow() (this=this@entry=0x56107ae77aa0, __in_chrg=<optimized out>) at /home/qt/work/qt/qtdeclarative/src/quick/items/qquickwindow.cpp:1119
#44 0x00007f2075e1b30a in QQuickWindowQmlImpl::~QQuickWindowQmlImpl() (this=0x56107ae77aa0, __in_chrg=<optimized out>)
    at /home/qt/work/qt/qtdeclarative/include/QtQuick/6.2.0/QtQuick/private/../../../../../src/quick/items/qquickwindowmodule_p.h:71
#45 QQmlPrivate::QQmlElement<QQuickWindowQmlImpl>::~QQmlElement() (this=0x56107ae77aa0, __in_chrg=<optimized out>) at /home/qt/work/qt/qtdeclarative/src/qml/qml/qqmlprivate.h:133
#46 QQmlPrivate::QQmlElement<QQuickWindowQmlImpl>::~QQmlElement() (this=0x56107ae77aa0, __in_chrg=<optimized out>) at /home/qt/work/qt/qtdeclarative/src/qml/qml/qqmlprivate.h:133
#47 0x00007f207458dbce in qDeleteAll<QList<QObject*>::const_iterator>(QList<QObject*>::const_iterator, QList<QObject*>::const_iterator) (end=..., begin=...) at /home/qt/work/install/include/QtCore/qalgorithms.h:59
#48 qDeleteAll<QList<QObject*> >(QList<QObject*> const&) (c=...) at /home/qt/work/install/include/QtCore/qalgorithms.h:67
#49 QQmlApplicationEnginePrivate::cleanUp() (this=this@entry=0x56107a9dcb60) at src/qml/qml/qqmlapplicationengine.cpp:66
#50 0x00007f207458dc19 in QQmlApplicationEngine::~QQmlApplicationEngine() (this=0x7ffff9543958, __in_chrg=<optimized out>) at src/qml/qml/qqmlapplicationengine.cpp:275
#51 0x000056107a078ccd in QmlEngineHolder::~QmlEngineHolder() (this=0x7ffff9543940, __in_chrg=<optimized out>) at ./qmlengineholder.cpp:29
```

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

No QA needed for this issue.
