### ISSUE TITLE
Background Service Error when trying to enable VPN under Arch Linux

### ISSUE THREAD

**Issue by xenanthropy** [mozilla-mobile/mozilla-vpn-client#555]
Downloading source and installing went fine - program launches ok but when I try to enable the VPN it turns on, displays "Background Service Error" then turns back off immediately. (Also, running `sudo mozillavpn linuxdaemon` produces no errors)
I was able to log into firefox through my browser and I successfully logged into the app, and my device shows up under the list of devices

Checking the logs: 
`[06.02.2021 12:32:36.249] (linux|controller - LinuxController) LinuxController activated`
`[06.02.2021 12:32:36.249] (linux - DBusClient) Activate via DBus`
`[06.02.2021 12:32:36.249] (main - MozillaVPN) Task completed`
`[06.02.2021 12:32:36.249] (main - MozillaVPN) Tasks:  0`
`[06.02.2021 12:32:36.280] (linux|controller - LinuxController) DBus service says: error.`
`[06.02.2021 12:32:36.280] (main - MozillaVPN) Handling error 4`
`[06.02.2021 12:32:36.281] (main - MozillaVPN) Alert: 5 State: 3`

That was the only thing I could see that looked like an issue of some sort (I've attached the log [**HERE**](https://github.com/mozilla-mobile/mozilla-vpn-client/files/5937462/mozillavpn-2021-2-6_2.txt) just in case)

I ran both test scripts and the first one (test_coverage.sh) passes completely, while the 2nd script (test_function.sh) successfully opens the VPN client, then errors out with this:

>This script runs the functional tests
>
>Retrieving mozillavpn version... /usr/bin/mozillavpn 2.0.3
>done.
>Running the app...
>done.
>Running the test: tests/functional/testAuthentication.js
>
>
> User authentication
>    1) reset the app
>    2) wait for the main view
>    3) Start and abort the authentication
>    ✓ quit the app (1000ms)
>
>
>  1 passing (3s)
>  3 failing
>
>  1) User authentication
>       reset the app:
>
>      AssertionError [ERR_ASSERTION]: Invalid answer
>      + expected - actual
>
>      -false
>      +true
>      
>      at Object.reset (tests/functional/helper.js:34:5)
>      at async Context.<anonymous> (tests/functional/testAuthentication.js:22:35)
>
>  2) User authentication
>       wait for the main view:
>
>      AssertionError [ERR_ASSERTION]: false == true
>      + expected - actual
>
>      -false
>      +true
>      
>      at Context.<anonymous> (tests/functional/testAuthentication.js:25:5)
>
>  3) User authentication
>       Start and abort the authentication:
>
>      AssertionError [ERR_ASSERTION]: Invalid answer
>      + expected - actual
>
>      -false
>      +true
>      
>      at Object.hasElement (tests/functional/helper.js:46:5)
>      at async Object.clickOnElement (tests/functional/helper.js:57:12)
>      at async Context.<anonymous> (tests/functional/testAuthentication.js:34:5)
>
>
>
>(node:505840) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added to >[Socket]. Use emitter.setMaxListeners() to increase limit
>(Use `node --trace-warnings ...` to show where the warning was created)
>/usr/lib/node_modules/mocha/lib/runner.js:873
>  throw err;
>  ^
>
>Error: Timeout for waitForCondition
>    at Object.waitForCondition (/home/conner/Desktop/mozillavpn/mozilla-vpn-client/tests/functional/helper.js:89:11)
>Nooo

**Info about packages used**
Kernel: 5.10.10-arch1-1
qt5: 5.15.2-3
dbus: 1.12.20-1
nodejs-mocha: 7.1.2-1

**Comment by xenanthropy** [comment]
Fixed the issue by rebooting... Something I don't do often under linux. Anyone with the same issues, I would suggest trying that.
