### ISSUE TITLE
[mobile] Error message displayed after subscribing via IAP

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#6078]
**Important details:** 

* after pressing the “Try again” button from the error screen, the user is redirected to the Onboarding screen. If signing out and back in, the user is redirected to the same error screen;

* the subscription is not displayed in [+FXA settings page+](https://accounts.stage.mozaws.net/settings); 
* “Confirm plan - Open this app to confirm your plan before…” text  is displayed in Google Play Store;

* “Your Google Play Order Receipt from..” email is received;

* reproducible on **production** server as well;
* **not** reproducing on 2.13.0 / 2.13.1 version (both stage and production servers);

**Affected versions:**

* 2.14.0 (2.202302162209);

* 2.14.0 (2.202302161835);

**Tested Platforms:**

* Android 10/11;

* iOS 16.2;

**Prerequisites:** 

* Have Mozilla VPN app installed and opened;

* Have a Fx account without subscription or create a new account;

* Be in IAP screen;

**Steps to reproduce:**

1. Select any price plan from the IAP screen and finalize the subscription;

**Expected result:**

* The subscription is finalized with success. The user is redirected to the activation screen;

**Actual result:**

* “Problem confirming subscription - An unexpected error has occurred, please try again. Visit our help center below to learn how to troubleshoot this issue or contact support” error message is displayed;

**Notes:**

* See the attached video and logs;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-4204)
┆Reporter: Bianca Hidecuti

**Comment by data-sync-user** [comment]
➤ Jeremy Swinarton commented:

Hi, I noticed that this is throwing a 500 on Guardian. I did some digging and found that the root error Guardian is throwing is this:

TypeError: Cannot read properties of undefined (reading 'user')
    at androidTokenValidation (file:///home/node/guardian-website/dist/controllers/api/iap-android.js:12:29)
    at file:///home/node/guardian-website/dist/middleware/index.js:3:25
    at Layer.handle [as handle_request] (/home/node/guardian-website/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/node/guardian-website/node_modules/express/lib/router/route.js:144:13)
    at /home/node/guardian-website/node_modules/body-parser/lib/read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (/home/node/guardian-website/node_modules/raw-body/index.js:231:16)
    at done (/home/node/guardian-website/node_modules/raw-body/index.js:220:7)
    at IncomingMessage.onEnd (/home/node/guardian-website/node_modules/raw-body/index.js:280:7)
    at IncomingMessage.emit (node:events:525:35)I have opened a PR to address this here ( https://github.com/mozilla-services/guardian-website/pull/1612 ). The root cause of this is that Guardian was originally designed to set Authorization token data on the session, making it optional for the client to send it after the first request (as long as the session is active). But there is a bug in Guardian that causes certain routes to return 500 in the event that an Authorization token is missing but the user data is available on the session.

My assumption, therefore, is that the Authorization token is not present on requests in client v2.14, which is why this works in previous versions. This Guardian fix will temporarily allow this, but my opinion is that we should not make the bearer token optional in the future as it can cause some serious confusion. I will open a new ticket shortly so we can discuss this and hopefully develop a plan to get the client sending the token on each request.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this as fixed on Mozilla VPN 2.14.0 (2.202302231536), using Android 11. The IAP subscription is finalized with success. The user is redirected to the activation screen. Attaching postfix video for the Android.

However, the issue is still reproducible on Mozilla VPN 2.14.0 (2.202302231836), while using iOS 16.2 → see the attached logs. Reopening this issue. 

!iap.mp4|width=1440,height=2880!

[^ios error MozillaVPN-logs.txt]

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Verified this as fixed on iOS 16.2 as well, while using Mozilla VPN 2.14.0 (2.202302271835). Attaching postfix video.

!2404.mp4|width=444,height=960!
