### ISSUE TITLE
Authentication in browser test fails

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#6098]
```
  User authentication in browser
Starting test: returns to main view on canceling authentication
Starting test: returns to main view on canceling authentication
    ✔ returns to main view on canceling authentication (545ms)
Starting test: Completes authentication
AssertionError [ERR_ASSERTION]: Command failed: undefined
    at Object.hardReset (/home/runner/work/mozilla-vpn-client/mozilla-vpn-client/tests/functional/helper.js:94:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Context.afterEach (/home/runner/work/mozilla-vpn-client/mozilla-vpn-client/tests/functional/setupVpn.js:179:7) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-4214)
┆Reporter: Andrea Marchesini

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

I can now replicate this bug on my Linux box by changing my /etc/hosts/ file by changing 

::1     ip6-localhost ip6-loopback

to 

::1     local ip6-localhost ip6-loopback

The route cause appears to be the DesktopAuthenticationListener not responding to IPv6 commands.

We have a quick fix https://github.com/mozilla-mobile/mozilla-vpn-client/pull/6141 ( https://github.com/mozilla-mobile/mozilla-vpn-client/pull/6141|smart-link )  and I will open a separate PR for a proper fix.
