### ISSUE TITLE
[Android] Crash at “Sign up” tap - Release APK only

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#7193]
**Important details:**

* Reproducing for both stage and prod servers;

**Mozilla VPN affected versions:**

* 2.16(2.202306121222);

**Platform tested:**

* Android 10/11;

**Prerequisites:**

* Have the Mozilla VPN app opened;

**Steps to reproduce:**

1. Tap the “Sign up” button;
1. Observe the behavior;

**Expected results:**

* Users are redirected to the email screen;

**Actual results:**

* App crashes;

**Notes:**

* attaching logs and video;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-5019)
┆Reporter: Valentina Virlics

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Attaching device logs as well. Beatriz Rizental Machado thanks for the help of obtaining them!

[^Android Logs-device.txt]

**Comment by data-sync-user** [comment]
➤ Beatriz Rizental Machado commented:

Note to self: this is the offending crash

FATAL EXCEPTION: pool-1-thread-1
                                                                                                    Process: org.mozilla.firefox.vpn, PID: 6460
                                                                                                    java.lang.NoSuchMethodError: No static method getTimeZone(Ljava/lang/String;)Ljava/util/TimeZone; in class Lj$/util/DesugarTimeZone; or its super classes (declaration of 'j$.util.DesugarTimeZone' appears in base.apk!classes2.dex)
                                                                                                    	at com.google.firebase.encoders.json.JsonDataEncoderBuilder$TimestampEncoder.<clinit>(JsonDataEncoderBuilder.java:54)
                                                                                                    	at com.google.firebase.encoders.json.JsonDataEncoderBuilder.<clinit>(JsonDataEncoderBuilder.java:65)
                                                                                                    	at com.google.android.datatransport.cct.internal.BatchedLogRequest.createDataEncoder(BatchedLogRequest.java:38)
                                                                                                    	at com.google.android.datatransport.cct.CctTransportBackend.<init>(CctTransportBackend.java:100)
                                                                                                    	at com.google.android.datatransport.cct.CctTransportBackend.<init>(CctTransportBackend.java:129)
                                                                                                    	at com.google.android.datatransport.cct.CctBackendFactory.create(CctBackendFactory.java:29)
                                                                                                    	at com.google.android.datatransport.runtime.backends.MetadataBackendRegistry.get(MetadataBackendRegistry.java:80)
                                                                                                    	at com.google.android.datatransport.runtime.scheduling.DefaultScheduler.lambda$schedule$1$DefaultScheduler(DefaultScheduler.java:70)
                                                                                                    	at com.google.android.datatransport.runtime.scheduling.-$$Lambda$DefaultScheduler$TUAu_XOWDlEdt54QDWOOZf2JNr8.run(Unknown Source:8)
                                                                                                    	at com.google.android.datatransport.runtime.SafeLoggingExecutor$SafeLoggingRunnable.run(SafeLoggingExecutor.java:47)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:919)
2023-06-14 11:35:54.838   918-4449  ActivityTaskManager     system_server                        W    Force finishing activity org.mozilla.firefox.vpn/.qt.VPNActivity

**Comment by data-sync-user** [comment]
➤ Beatriz Rizental Machado commented:

The DesugarTimeZone class contains the getTimeZone method starting from desugar_jdk_libs v1.0.10 ( https://github.com/google/desugar_jdk_libs/blob/master/CHANGELOG.md#version-1010-2020-07-28 ), which annoyingly is exactly the version of the library we use ( https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/android/buildSrc/src/main/kotlin/Dependencies.kt#L9 ).

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this as fixed while using 2.16 (2.202306151643) build on Android 10.

Sign in is possible on both stage and prod. Mozilla VPN can be turned ON and works as expected.
