### ISSUE TITLE
Taskcluster is failing to build for iOS

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/mozilla-vpn-client#7440]
This seems to currently be happening in all branches. See example on: [https://github.com/mozilla-mobile/mozilla-vpn-client/runs/14823926506](https://github.com/mozilla-mobile/mozilla-vpn-client/runs/14823926506|smart-link) 

```
Extracting /opt/worker/tasks/task_168864029996571/fetches/qt6_ios.zip to /opt/worker/tasks/task_168864029996571/fetches
qt_ios/6.2.4/macos/lib/libQt6QmlDom.a:  write error (disk full?).  Continue? (y/n/^C) 
warning:  qt_ios/6.2.4/macos/lib/libQt6QmlDom.a is probably truncated
Traceback (most recent call last):
  File "fetch-content", line 899, in <module>
    sys.exit(main())
  File "fetch-content", line 895, in main
    return args.func(args)
  File "fetch-content", line 801, in command_task_artifacts
[taskcluster 2023-07-06T11:30:30.779Z]    Exit Code: 120
[taskcluster 2023-07-06T11:30:30.779Z]    User Time: 1m41.637418s
[taskcluster 2023-07-06T11:30:30.779Z]  Kernel Time: 49.283462s
[taskcluster 2023-07-06T11:30:30.779Z]    Wall Time: 2m47.740187s
[taskcluster 2023-07-06T11:30:30.779Z]       Result: FAILED
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-5180)
┆Reporter: Beatriz Rizental Machado

**Comment by data-sync-user** [comment]
➤ Beatriz Rizental Machado commented:

This is a RELOPS issue. See duplicate.

**Comment by data-sync-user** [comment]
➤ Beatriz Rizental Machado commented:

This has stopped happening. Closing.
